apiVersion: v1
kind: Service
metadata:
  name: {{ include "willog-demo.fullname" . }}
  labels:
    {{- include "willog-demo.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "willog-demo.selectorLabels" . | nindent 4 }}
